/**
 * Biwse API V1 Reference
 * This API documentation generated from OpenAPI specification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AppInvoice model module.
 * @module model/AppInvoice
 * @version 1.0.0
 */
class AppInvoice {
    /**
     * Constructs a new <code>AppInvoice</code>.
     * @alias module:model/AppInvoice
     * @param amountUsd {Number} Invoice's amount
     */
    constructor(amountUsd) { 
        
        AppInvoice.initialize(this, amountUsd);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amountUsd) { 
        obj['amount_usd'] = amountUsd;
    }

    /**
     * Constructs a <code>AppInvoice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppInvoice} obj Optional instance to populate.
     * @return {module:model/AppInvoice} The populated <code>AppInvoice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppInvoice();

            if (data.hasOwnProperty('amount_usd')) {
                obj['amount_usd'] = ApiClient.convertToType(data['amount_usd'], 'Number');
            }
            if (data.hasOwnProperty('callback_link')) {
                obj['callback_link'] = ApiClient.convertToType(data['callback_link'], 'String');
            }
            if (data.hasOwnProperty('success_url')) {
                obj['success_url'] = ApiClient.convertToType(data['success_url'], 'String');
            }
            if (data.hasOwnProperty('invoice_number')) {
                obj['invoice_number'] = ApiClient.convertToType(data['invoice_number'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Invoice's amount
 * @member {Number} amount_usd
 */
AppInvoice.prototype['amount_usd'] = undefined;

/**
 * Callback url
 * @member {String} callback_link
 */
AppInvoice.prototype['callback_link'] = undefined;

/**
 * Redirect user after payment
 * @member {String} success_url
 */
AppInvoice.prototype['success_url'] = undefined;

/**
 * Your invoice internal identifier
 * @member {String} invoice_number
 */
AppInvoice.prototype['invoice_number'] = undefined;






export default AppInvoice;

