/**
 * Biwse API V1 Reference
 * This API documentation generated from OpenAPI specification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvoiceStatusData model module.
 * @module model/InvoiceStatusData
 * @version 1.0.0
 */
class InvoiceStatusData {
    /**
     * Constructs a new <code>InvoiceStatusData</code>.
     * @alias module:model/InvoiceStatusData
     */
    constructor() { 
        
        InvoiceStatusData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvoiceStatusData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvoiceStatusData} obj Optional instance to populate.
     * @return {module:model/InvoiceStatusData} The populated <code>InvoiceStatusData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvoiceStatusData();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('confs')) {
                obj['confs'] = ApiClient.convertToType(data['confs'], 'Number');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('tx_hash')) {
                obj['tx_hash'] = ApiClient.convertToType(data['tx_hash'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Boolean');
            }
            if (data.hasOwnProperty('accepted')) {
                obj['accepted'] = ApiClient.convertToType(data['accepted'], 'Boolean');
            }
            if (data.hasOwnProperty('verification_hash')) {
                obj['verification_hash'] = ApiClient.convertToType(data['verification_hash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Invoice's amount
 * @member {Number} amount
 */
InvoiceStatusData.prototype['amount'] = undefined;

/**
 * Number of transaction confirmations
 * @member {Number} confs
 */
InvoiceStatusData.prototype['confs'] = undefined;

/**
 * Payment receieved on address
 * @member {String} address
 */
InvoiceStatusData.prototype['address'] = undefined;

/**
 * Transaction hash
 * @member {String} tx_hash
 */
InvoiceStatusData.prototype['tx_hash'] = undefined;

/**
 * Currency type
 * @member {Boolean} type
 */
InvoiceStatusData.prototype['type'] = undefined;

/**
 * Payment accepted or not
 * @member {Boolean} accepted
 */
InvoiceStatusData.prototype['accepted'] = undefined;

/**
 * Verification hash
 * @member {String} verification_hash
 */
InvoiceStatusData.prototype['verification_hash'] = undefined;






export default InvoiceStatusData;

