/**
 * Biwse API V1 Reference
 * This API documentation generated from OpenAPI specification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Payment from './Payment';

/**
 * The Payments model module.
 * @module model/Payments
 * @version 1.0.0
 */
class Payments {
    /**
     * Constructs a new <code>Payments</code>.
     * @alias module:model/Payments
     */
    constructor() { 
        
        Payments.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Payments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Payments} obj Optional instance to populate.
     * @return {module:model/Payments} The populated <code>Payments</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Payments();

            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], [Payment]);
            }
        }
        return obj;
    }


}

/**
 * Payments array
 * @member {Array.<module:model/Payment>} payments
 */
Payments.prototype['payments'] = undefined;






export default Payments;

