/**
 * Biwse API V1 Reference
 * This API documentation generated from OpenAPI specification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WalletBalance model module.
 * @module model/WalletBalance
 * @version 1.0.0
 */
class WalletBalance {
    /**
     * Constructs a new <code>WalletBalance</code>.
     * @alias module:model/WalletBalance
     */
    constructor() { 
        
        WalletBalance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WalletBalance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WalletBalance} obj Optional instance to populate.
     * @return {module:model/WalletBalance} The populated <code>WalletBalance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WalletBalance();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('confirmed')) {
                obj['confirmed'] = ApiClient.convertToType(data['confirmed'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Total wallet balance.
 * @member {Number} total
 */
WalletBalance.prototype['total'] = undefined;

/**
 * Fund in wallet available to withdrawal.
 * @member {Number} confirmed
 */
WalletBalance.prototype['confirmed'] = undefined;






export default WalletBalance;

