/**
 * Biwse API V1 Reference
 * This API documentation generated from OpenAPI specification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WalletInvoice model module.
 * @module model/WalletInvoice
 * @version 1.0.0
 */
class WalletInvoice {
    /**
     * Constructs a new <code>WalletInvoice</code>.
     * @alias module:model/WalletInvoice
     * @param amount {Number} Invoice's amount
     */
    constructor(amount) { 
        
        WalletInvoice.initialize(this, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount) { 
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>WalletInvoice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WalletInvoice} obj Optional instance to populate.
     * @return {module:model/WalletInvoice} The populated <code>WalletInvoice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WalletInvoice();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('callback_link')) {
                obj['callback_link'] = ApiClient.convertToType(data['callback_link'], 'String');
            }
            if (data.hasOwnProperty('success_url')) {
                obj['success_url'] = ApiClient.convertToType(data['success_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Invoice's amount
 * @member {Number} amount
 */
WalletInvoice.prototype['amount'] = undefined;

/**
 * Callback url
 * @member {String} callback_link
 */
WalletInvoice.prototype['callback_link'] = undefined;

/**
 * Redirect user after payment
 * @member {String} success_url
 */
WalletInvoice.prototype['success_url'] = undefined;






export default WalletInvoice;

